// <auto-generated />
namespace Naruto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyCheckServers_IP_to200 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyCheckServers_IP_to200));
        
        string IMigrationMetadata.Id
        {
            get { return "201712281035259_modifyCheckServers_IP_to200"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
