// <auto-generated />
namespace Naruto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170323_modifyCheckServer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170323_modifyCheckServer));
        
        string IMigrationMetadata.Id
        {
            get { return "201703230245215_20170323_modifyCheckServer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
