// <auto-generated />
namespace Naruto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyCheckServers_updatetime_allowNULL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyCheckServers_updatetime_allowNULL));
        
        string IMigrationMetadata.Id
        {
            get { return "201705260225551_modifyCheckServers_updatetime_allowNULL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
