// <auto-generated />
namespace Naruto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170323_changeName_from_CheckReporItems_to_CheckReportSummaries_addTable_CheckReporItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170323_changeName_from_CheckReporItems_to_CheckReportSummaries_addTable_CheckReporItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201703230321334_20170323_changeName_from_CheckReporItems_to_CheckReportSummaries_addTable_CheckReporItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
